%rename(CurveProjectionFailed) BRepBuilderAPI_CurveProjectionFailed;
%rename(EmptyShell) BRepBuilderAPI_EmptyShell;
%rename(FindPlane) BRepBuilderAPI_FindPlane;
%rename(MakeFace) BRepBuilderAPI_MakeFace;
%rename(DisconnectedWire) BRepBuilderAPI_DisconnectedWire;
%rename(MakeEdge2d) BRepBuilderAPI_MakeEdge2d;
%rename(Transformed) BRepBuilderAPI_Transformed;
%rename(Preserved) BRepBuilderAPI_Preserved;
%rename(MakeShell) BRepBuilderAPI_MakeShell;
%rename(Merged) BRepBuilderAPI_Merged;
%rename(BoundaryModified) BRepBuilderAPI_BoundaryModified;
%rename(GTransform) BRepBuilderAPI_GTransform;
%rename(ImpossibleContact) BRepBuilderAPI_ImpossibleContact;
%rename(EmptyWire) BRepBuilderAPI_EmptyWire;
%rename(ParametersOutOfRange) BRepBuilderAPI_ParametersOutOfRange;
%rename(FaceDone) BRepBuilderAPI_FaceDone;
%rename(Deleted) BRepBuilderAPI_Deleted;
%rename(Sewing) BRepBuilderAPI_Sewing;
%rename(ShellParametersOutOfRange) BRepBuilderAPI_ShellParametersOutOfRange;
%rename(ModifyShape) BRepBuilderAPI_ModifyShape;
%rename(SurfaceNotC2) BRepBuilderAPI_SurfaceNotC2;
%rename(MakeShape) BRepBuilderAPI_MakeShape;
%rename(DifferentPointsOnClosedCurve) BRepBuilderAPI_DifferentPointsOnClosedCurve;
%rename(MakeSolid) BRepBuilderAPI_MakeSolid;
%rename(PointWithInfiniteParameter) BRepBuilderAPI_PointWithInfiniteParameter;
%rename(Copy) BRepBuilderAPI_Copy;
%rename(RightCorner) BRepBuilderAPI_RightCorner;
%rename(WireDone) BRepBuilderAPI_WireDone;
%rename(NoFace) BRepBuilderAPI_NoFace;
%rename(NotPlanar) BRepBuilderAPI_NotPlanar;
%rename(MakeEdge) BRepBuilderAPI_MakeEdge;
%rename(Transform) BRepBuilderAPI_Transform;
%rename(ParameterOutOfRange) BRepBuilderAPI_ParameterOutOfRange;
%rename(Trimmed) BRepBuilderAPI_Trimmed;
%rename(EdgeDone) BRepBuilderAPI_EdgeDone;
%rename(Command) BRepBuilderAPI_Command;
%rename(MakeWire) BRepBuilderAPI_MakeWire;
%rename(DifferentsPointAndParameter) BRepBuilderAPI_DifferentsPointAndParameter;
%rename(BRepBuilderAPI) BRepBuilderAPI;
%rename(PipeDone) BRepBuilderAPI_PipeDone;
%rename(NonManifoldWire) BRepBuilderAPI_NonManifoldWire;
%rename(NurbsConvert) BRepBuilderAPI_NurbsConvert;
%rename(DisconnectedShell) BRepBuilderAPI_DisconnectedShell;
%rename(Collect) BRepBuilderAPI_Collect;
%rename(PlaneNotIntersectGuide) BRepBuilderAPI_PlaneNotIntersectGuide;
%rename(LineThroughIdenticPoints) BRepBuilderAPI_LineThroughIdenticPoints;
%rename(PipeNotDone) BRepBuilderAPI_PipeNotDone;
%rename(MakeVertex) BRepBuilderAPI_MakeVertex;
%rename(Handle_Sewing) Handle_BRepBuilderAPI_Sewing;
%rename(ShellDone) BRepBuilderAPI_ShellDone;
%rename(MakePolygon) BRepBuilderAPI_MakePolygon;
%rename(RoundCorner) BRepBuilderAPI_RoundCorner;
%rename(PointProjectionFailed) BRepBuilderAPI_PointProjectionFailed;
